### ISSUE TITLE
[BUG] Time.bat运行错误

### ISSUE THREAD

**Issue by Chen-Junren** [Chen-Junren/Python-Weather#13]
#### 为避免无效问题和冗余问题，提问前请确认

- [ ] 你确定Google不能解决你的问题
- [x] 你确定已有的issue不能解决你的问题
- [x] 你确定issue的title按照格式如下：错误代码：简略解释

---

#### 如何重现问题
_把你遇到的问题的发生步骤替换掉下面的内容_
1. 在Win10系统下下载Win7版本的文件并解压
2. 执行Time.bat，发现无法成功
3. 
---

#### 期待修复的效果
_替换下面的内容_
修复BUG...

---

#### 如有必要，可以截图说明：

---

#### 环境版本说明：
操作系统：Win10
相关库/包的版本：V3.1.2
如果有必要，说明浏览器型号：

---

#### 其他说明 
_添加你认为有必要的内容，否则不写。_
初步认为是Win7与Win10的文件默认保存编码不同导致的错误

**Comment by cjr1030** [comment]
计划将原bat打包成exe以避免编码问题

**Comment by cjr1030** [comment]
已解决问题，将在V3.1.3的更新中修复
